db:
        image: mysql:5.7
        restart: always
        environment:
                MYSQL_ROOT_PASSWORD: root
web:
        build: php-7.1
        ports:
                - 8080:80
        links:
                - db
